# Generated by Django 5.1.6 on 2025-05-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercourse',
            table='user_course',
        ),
    ]
