# Generated by Django 5.1.6 on 2025-03-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lesson_created_at_alter_lesson_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='example_vi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
