# Generated by Django 5.1.6 on 2025-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
