# Generated by Django 5.1.6 on 2025-03-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_word_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='cefr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
