# Generated by Django 5.1.6 on 2025-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_lesson_code_course_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='en_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
