# Generated by Django 5.1.6 on 2025-05-03 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('streak', models.IntegerField(default=0)),
                ('completed_lessons', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('completed_topics', models.IntegerField(default=0)),
                ('total_topics', models.IntegerField(default=0)),
                ('learning_time', models.DurationField(default=0)),
                ('subscription', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
                'db_table': 'user_detail',
                'ordering': ['-joined_date'],
            },
        ),
    ]
