version: '3.8'

services:
  web:
    image: ${DOCKER_IMAGE}
    container_name: lingual_be
    restart: always
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
    networks:
      - app_network
      - web_net


  db:
    image: postgres:17
    container_name: lingual_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - lingual_db_data:/var/lib/postgresql/data
    networks:
      - app_network
      - web_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    container_name: lingual_redis
    restart: always
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3


networks:
  app_network:
    driver: bridge
  web_net:
    external: true

volumes:
  lingual_db_data: