# docker-compose.yml (root)
version: '3.8'

services:
  web:
#    image: ${DOCKER_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
#    env_file:
#      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - check-db
      - redis
    networks:
      - app_network

  check-db:
    image: alpine:3.18
    command: >
      sh -c "
      until nc -z -v -w30 ${DATABASE_HOST} ${DATABASE_PORT};
      do sleep 5;
      done
      "
  redis:
    image: redis:latest
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app_network:
    driver: bridge