version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env.local
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    networks:
      - app_network
      - web_net

  db:
    image: postgres:17
    container_name: lingual_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - lingual_db_data:/var/lib/postgresql/data
    networks:
      - app_network
      - web_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      
  redis:
    image: redis:latest
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app_network:
    driver: bridge
  web_net:
    external: true

volumes:
  lingual_db_data: