version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/.venv
      - /app/__pycache__
    environment:
      - DJANGO_DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000