version: '3.8'

services:
  web:
    image: ${DOCKER_IMAGE}
    restart: always
    env_file:
      - ./.env
    depends_on:
      - check-db
      - redis
    networks:
      - app_network
      - web_net

  check-db:
    image: alpine:3.18
    command: >
      sh -c "
      until nc -z -v -w30 ${DATABASE_HOST} ${DATABASE_PORT};
      do sleep 5;
      done
      "
    networks:
      - app_network

  redis:
    image: redis:latest
    restart: always
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app_network:
    driver: bridge
  web_net:
    external: true