# Generated by Django 5.1.6 on 2025-06-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userdetail_learning_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AddField(
            model_name='userdetail',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='accounts_customuser',
        ),
    ]
